# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magnet',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('magnet', models.TextField()),
                ('reg_dated', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
