# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magnet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=200, null=True)),
                ('title', models.TextField()),
                ('magnet', models.TextField()),
                ('reg_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
