# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_auto_20170410_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
