# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_magnet_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magnet',
            old_name='reg_dated',
            new_name='reg_date',
        ),
    ]
