# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0003_auto_20170410_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magnet',
            name='magnet',
        ),
        migrations.AlterField(
            model_name='magnet',
            name='url',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
