# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0004_auto_20170410_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnet',
            name='magnet',
            field=models.TextField(default='magnet'),
            preserve_default=False,
        ),
    ]
