# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0005_magnet_magnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnet',
            name='category',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
