# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0007_auto_20170411_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnet',
            name='reg_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 4, 13, 13, 9, 24, 482514)),
        ),
    ]
