# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0008_auto_20170413_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnet',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
